import { Resend } from 'resend'
import { NextResponse } from 'next/server'

export async function POST(request: Request) {
  console.log('Security alert email API route hit!')
  try {
    const body = await request.json().catch(() => ({}))
    const title = body.title || 'Security Incident Alert'
    const description = body.description || 'A critical security incident has been flagged by EagleEye monitoring.'
    const recipientEmail = process.env.ALERT_RECIPIENT_EMAIL || 'graceshao203@gmail.com'

    // If Resend API Key is available, send actual email
    if (process.env.RESEND_API_KEY) {
      const resend = new Resend(process.env.RESEND_API_KEY)
      console.log(`Sending email via Resend to: ${recipientEmail}`)

      const { data, error } = await resend.emails.send({
        from: 'EagleEye <onboarding@resend.dev>',
        to: [recipientEmail],
        subject: `[ALERT] ${title}`,
        html: `
          <h2>${title}</h2>
          <p>${description}</p>
          <p><em>This alert was generated by EagleEye's real-time security monitoring system.</em></p>
        `
      })

      if (error) {
        console.error('Resend API error:', error)
        return NextResponse.json({ success: false, error }, { status: 500 })
      }
      console.log('Security alert email sent successfully:', data)
      return NextResponse.json({ success: true, data })
    }

    // Simulated email dispatch if RESEND_API_KEY is not set
    console.log(`[SIMULATION] Security alert logged for ${recipientEmail}: ${title} - ${description}`)
    return NextResponse.json({
      success: true,
      simulated: true,
      message: `Security alert dispatched successfully for: ${title}`,
      data: { id: `sim_${Date.now()}` }
    })
  } catch (error) {
    console.error('Unexpected error in email API:', error)
    return NextResponse.json({
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error'
    }, { status: 500 })
  }
}
